### ISSUE TITLE
Asks for license

### ISSUE THREAD

**Issue by ccolas** [colorio-dev/colorio#207]
Hello,
Importing colorio in python now gives me a warning:
```
Warning: Unable to find valid license in
- environment variable COLORIO_LICENSE_KEY (env var not found), or
- config file .../colorio/colorio.toml (file not found)
```

Is this software not open source anymore?

**Comment by nschloe** [comment]
Just update the issue should go away.

**Comment by shankarsivarajan** [comment]
> Is this software not open source anymore?

The nice thing about most open source licenses (including the one this used to licensed under) is that the rights are irrevocable. You just need to find an older fork, of which there are plenty.

**Comment by Lucas-nac27** [comment]
How do I try this product for free?

**Comment by nschloe** [comment]
@Lucas-nac27 Mail to support@mondaytech.com.
